stages:
  - build
  - deploy

variables:
  IMAGE_TAG: ada26/ktx-db:$CI_COMMIT_SHORT_SHA 

build-deploy-db:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Đang build image cho DB..."
  script:
    - cd db
    - docker build -t $IMAGE_TAG .  
    - docker push $IMAGE_TAG  
  rules:
    - changes:
        - db/**/*  

deploy-db:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_DB" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - echo "Triển khai DB lên EC2..."
    - ssh -o StrictHostKeyChecking=no ec2-user@$DB_EC2_IP "
        docker pull $IMAGE_TAG;
        docker stop db_container || true;
        docker rm db_container || true;
        docker rmi \$(docker images -q --filter reference='ada26/ktx-db') || true;
        docker run -d --name db_container $IMAGE_TAG;
      "
  rules:
    - changes:
        - db/**/*
