// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
// `.env.ts` is generated by the `npm run env` command 192.168.1.72:4200
import env from './.env';

export const environment: any = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: {
    // sys: 'http://localhost:8685',
    // sys: 'http://42.116.46.57:8685',
    sys: 'http://localhost:8888',
  },
};
